### ISSUE TITLE
Why does WP ecosystem dislike namespaces?

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/twentytwentyone-dark-mode#22]
```php
// Was
function tt1_dark_mode_switch_the_styles() {

// Becomes
namespace WordPress\Twenty_Twenty_One\Dark_Mode_Switch;
function the_styles() {
```

What do you think?

You can't say _PHP compatibility_! :)

**Comment by szepeviktor** [comment]
Too high level of entry??
Theme developers object to reading php.net?

**Comment by aristath** [comment]
:rofl: It's partly tradition, WP until recently had to support WP5.2 so most WP developers are not yet used to building things using namespaces. Plugins & Themes use namespaces a lot, however since the TwentyTwentyOne theme will be part of WP-Core it should follow the WP-Core rules.
It has been suggested many times to introduce namespaces in WP-Core, the argument is always the same: There should be a plan and it should happen everywhere, all at once. :shrug: All discussions usually stop there since there is no plan (yet) to modernize parts of WP Core's code, and **one of the principles for core is to not refactor something for the sake of refactoring**. So it's a catch-22: People want the change to happen everywhere at once, and they want code consistency. But refactoring for the sake of refactoring is frowned upon and considered bad practice. At the same time, all new code in WP is supposed to follow modern standards, and since ~10-20% of code is touched on each release the logic is that over time 100% will be refactored. But that doesn't make any sense for things like namespaces... 
If you manage to find a logical solution to this conundrum do let me know and a plan can start to take form so we can get it done.
Backwards-compatibility is not an issue with namespaced classes since we can keep references to old classnames using `class_alias`.

**Comment by aristath** [comment]
Closed the ticket since it's not something actionable, we can keep it as a discussion thread :wink:

**Comment by szepeviktor** [comment]
Thank you for your long answer.

**Comment by szepeviktor** [comment]
High quality (structured) code seems to be fighting a battle 🥊🥊🥊 with popularity.
That is the birth place of WordPress.

**Comment by aristath** [comment]
:+1: This is one of the things that are always on my mind and I'm trying to slowly formulate a plan but so far I haven't been able to find a viable, satisfactory  solution. If you think of something do let me know... Like you, I think it is important
